name: Deploy Eleventy to GitHub Pages

on:
  push:
    branches: ["main"] # 自分のブランチ名に合わせてね

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build Eleventy
        run: npx @11ty/eleventy
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site' # 11tyの出力フォルダ名
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4